apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-11-25T14:03:09Z"
    labels:
      component: apiserver
      provider: kubernetes
    name: kubernetes
    namespace: default
    resourceVersion: "229"
    uid: ee43cb5d-0311-47fb-ba29-016c0c92393d
  spec:
    clusterIP: 10.96.0.1
    clusterIPs:
    - 10.96.0.1
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2024-11-25T15:38:31Z"
    labels:
      app: myapp
    name: myapp
    namespace: default
    resourceVersion: "9593"
    uid: 110ac4e1-f861-44ae-9aab-fd51131c855f
  spec:
    clusterIP: 10.96.154.230
    clusterIPs:
    - 10.96.154.230
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 30001
      port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: myapp
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
